default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: immunity_development

test:
  <<: *default
  database: immunity_test

production:
  <<: *default
  database: immunity_production
  username: immunity
  password: <%= ENV['IMMUNITY_DATABASE_PASSWORD'] %>
