# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4722275b079587e6069cff038193b24c8a86781609945df5c9bcd011ffa4a9a2e921d0f33bb55533d598eab0841127106dc03e9940f4f865071c80078dada03d

test:
  secret_key_base: c2e99da2eed05d0a000b65c9814998d46ba60555cc93df97803a7ecebf69877cd56a0afa4a612e46337c954541545af69c1ad0478d5d9bc60f4ebc901ce54762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
